In [11]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

print("Its alive!")

Its alive!

In [12]:
#Functions

In [13]:
drop_list = []
df = pd.read_csv("./Utah_Crash_Data_2020.csv")
df = df.drop([
"CRASH_ID",
# "CRASH_DATETIME",
# "CRASH_SEVERITY_ID",
"ROUTE",
"MILEPOINT",
"LAT_UTM_Y",
"LONG_UTM_X",
"MAIN_ROAD_NAME",  
"CITY",                              
"COUNTY_NAME",                       
"WORK_ZONE_RELATED",                 
"PEDESTRIAN_INVOLVED",               
"BICYCLIST_INVOLVED",                
"MOTORCYCLE_INVOLVED",               
"IMPROPER_RESTRAINT",                
"UNRESTRAINED",                      
"DUI",                               
"INTERSECTION_RELATED",              
"WILD_ANIMAL_RELATED",               
"DOMESTIC_ANIMAL_RELATED",           
"OVERTURN_ROLLOVER",                 
"COMMERCIAL_MOTOR_VEH_INVOLVED",     
"TEENAGE_DRIVER_INVOLVED",           
"OLDER_DRIVER_INVOLVED",             
"NIGHT_DARK_CONDITION",              
"SINGLE_VEHICLE",                    
"DISTRACTED_DRIVING",                
"DROWSY_DRIVING",                   
"ROADWAY_DEPARTURE"
], axis=1)
df = df.dropna()

C:\Users\whyri\AppData\Local\Temp\ipykernel_33368\98068382.py:2: DtypeWarning: Columns (0,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./Utah_Crash_Data_2020.csv")

In [14]:
#Takes around 2:30 min to run
# df["CRASH_MONTH"] = pd.to_datetime(df["CRASH_DATETIME"]).dt.month
# df["CRASH_WEEKDAY"] = pd.to_datetime(df["CRASH_DATETIME"]).dt.day_name()
df["CRASH_HOUR"] = pd.to_datetime(df["CRASH_DATETIME"]).dt.hour

df = df[df["CRASH_SEVERITY_ID"] >= 4]
df = df.drop(columns=["CRASH_DATETIME","CRASH_SEVERITY_ID"])

In [15]:
df_agg = df.groupby(['CRASH_HOUR']).size().reset_index(name="COUNT")
#Although the below columns are numeric, they are categorical because they are a time not a measurement
df_agg = pd.get_dummies(df_agg, columns=["CRASH_HOUR"])
df_agg.set_index("COUNT")

,CRASH_HOUR_0,CRASH_HOUR_1,CRASH_HOUR_2,CRASH_HOUR_3,CRASH_HOUR_4,CRASH_HOUR_5,CRASH_HOUR_6,CRASH_HOUR_7,CRASH_HOUR_8,CRASH_HOUR_9,...,CRASH_HOUR_14,CRASH_HOUR_15,CRASH_HOUR_16,CRASH_HOUR_17,CRASH_HOUR_18,CRASH_HOUR_19,CRASH_HOUR_20,CRASH_HOUR_21,CRASH_HOUR_22,CRASH_HOUR_23
COUNT,,,,,,,,,,,,,,,,,,,,,
134,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
189,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
265,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
225,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
179,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
192,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
296,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
395,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
399,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
408,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
292,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
238,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
245,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
180,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
# Split dataset in features and target variable

y = df_agg["COUNT"] # Label
X = df_agg.drop(columns=["COUNT"]) # Features
X.head()

,CRASH_HOUR_0,CRASH_HOUR_1,CRASH_HOUR_2,CRASH_HOUR_3,CRASH_HOUR_4,CRASH_HOUR_5,CRASH_HOUR_6,CRASH_HOUR_7,CRASH_HOUR_8,CRASH_HOUR_9,...,CRASH_HOUR_14,CRASH_HOUR_15,CRASH_HOUR_16,CRASH_HOUR_17,CRASH_HOUR_18,CRASH_HOUR_19,CRASH_HOUR_20,CRASH_HOUR_21,CRASH_HOUR_22,CRASH_HOUR_23
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# Set label and features
y = df_agg["COUNT"] # Label
X = df_agg.drop(columns=["COUNT"]) # Features

# Run the multiple linear regression model
model = sm.OLS(y, X).fit()

# View results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  COUNT   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Wed, 06 Apr 2022   Prob (F-statistic):                nan
Time:                        00:02:16   Log-Likelihood:                    inf
No. Observations:                  24   AIC:                              -inf
Df Residuals:                       0   BIC:                              -inf
Df Model:                          23
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
CRASH_HOUR_0    134.0000        nan        nan        nan         nan         nan
CRASH_HOUR_1    102.0000        nan        nan        nan         nan         nan
CRASH_HOUR_2     75.0000        nan        nan        nan         nan         nan
CRASH_HOUR_3     60.0000        nan        nan        nan         nan         nan
CRASH_HOUR_4     60.0000        nan        nan        nan         nan         nan
CRASH_HOUR_5    113.0000        nan        nan        nan         nan         nan
CRASH_HOUR_6    189.0000        nan        nan        nan         nan         nan
CRASH_HOUR_7    265.0000        nan        nan        nan         nan         nan
CRASH_HOUR_8    225.0000        nan        nan        nan         nan         nan
CRASH_HOUR_9    179.0000        nan        nan        nan         nan         nan
CRASH_HOUR_10   192.0000        nan        nan        nan         nan         nan
CRASH_HOUR_11   296.0000        nan        nan        nan         nan         nan
CRASH_HOUR_12   329.0000        nan        nan        nan         nan         nan
CRASH_HOUR_13   323.0000        nan        nan        nan         nan         nan
CRASH_HOUR_14   395.0000        nan        nan        nan         nan         nan
CRASH_HOUR_15   399.0000        nan        nan        nan         nan         nan
CRASH_HOUR_16   408.0000        nan        nan        nan         nan         nan
CRASH_HOUR_17   434.0000        nan        nan        nan         nan         nan
CRASH_HOUR_18   382.0000        nan        nan        nan         nan         nan
CRASH_HOUR_19   292.0000        nan        nan        nan         nan         nan
CRASH_HOUR_20   238.0000        nan        nan        nan         nan         nan
CRASH_HOUR_21   245.0000        nan        nan        nan         nan         nan
CRASH_HOUR_22   180.0000        nan        nan        nan         nan         nan
CRASH_HOUR_23   137.0000        nan        nan        nan         nan         nan
==============================================================================
Omnibus:                      429.259   Durbin-Watson:                     nan
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                9.000
Skew:                           0.000   Prob(JB):                       0.0111
Kurtosis:                       0.000   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

c:\Users\whyri\OneDrive\Desktop\intex_python\ml-venv2\lib\site-packages\statsmodels\regression\linear_model.py:1749: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
c:\Users\whyri\OneDrive\Desktop\intex_python\ml-venv2\lib\site-packages\statsmodels\regression\linear_model.py:1749: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
c:\Users\whyri\OneDrive\Desktop\intex_python\ml-venv2\lib\site-packages\statsmodels\regression\linear_model.py:924: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
c:\Users\whyri\OneDrive\Desktop\intex_python\ml-venv2\lib\site-packages\statsmodels\stats\stattools.py:50: RuntimeWarning: invalid value encountered in double_scalars
  dw = np.sum(diff_resids**2, axis=axis) / np.sum(resids**2, axis=axis)
c:\Users\whyri\OneDrive\Desktop\intex_python\ml-venv2\lib\site-packages\statsmodels\regression\linear_model.py:1671: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [18]:
df_insample = pd.DataFrame({'Actual':df_agg['COUNT'], 
                    'Predicted':model.fittedvalues, 
                    'Residuals (Error)':df_agg['COUNT'] - model.fittedvalues})

df_insample.head(10)

   Actual  Predicted  Residuals (Error)
0     134      134.0                0.0
1     102      102.0                0.0
2      75       75.0                0.0
3      60       60.0                0.0
4      60       60.0                0.0
5     113      113.0                0.0
6     189      189.0                0.0
7     265      265.0                0.0
8     225      225.0                0.0
9     179      179.0                0.0

In [19]:
def regression_fit(model, y_actual):

    y_pred = model.fittedvalues

    print(f"R2:\t{round(model.rsquared, 4)}")
    print(f"R2-adj:\t{round(model.rsquared_adj, 4)}")
    print(f"MAE:\t{round(abs(y_pred - y_actual).mean(), 4)}")
    print(f"RMSE:\t{round(((y_pred - y_actual)**2).mean() ** (1/2), 4)}")

regression_fit(model, y)

R2:	1.0
R2-adj:	nan
MAE:	0.0
RMSE:	0.0

In [20]:
print("MAX: ", df_agg['COUNT'].max())
print("MIN: ", df_agg['COUNT'].min())
print("MEAN: ", df_agg['COUNT'].mean())
print("MEDIAN: ", df_agg['COUNT'].median())

MAX:  434
MIN:  60
MEAN:  235.5
MEDIAN:  231.5