In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

print("Its alive!")

Its alive!

In [16]:
#Functions

In [7]:
drop_list = []
df = pd.read_csv("./Utah_Crash_Data_2020.csv")
df = df.drop([
"CRASH_ID",
# "CRASH_DATETIME",
# "CRASH_SEVERITY_ID",
"ROUTE",
"MILEPOINT",
"LAT_UTM_Y",
"LONG_UTM_X",
"MAIN_ROAD_NAME",  
"CITY",                              
"COUNTY_NAME",                       
# "WORK_ZONE_RELATED",                 
# "PEDESTRIAN_INVOLVED",               
# "BICYCLIST_INVOLVED",                
# "MOTORCYCLE_INVOLVED",               
# "IMPROPER_RESTRAINT",                
# "UNRESTRAINED",                      
# "DUI",                               
# "INTERSECTION_RELATED",              
# "WILD_ANIMAL_RELATED",               
# "DOMESTIC_ANIMAL_RELATED",           
# "OVERTURN_ROLLOVER",                 
# "COMMERCIAL_MOTOR_VEH_INVOLVED",     
# "TEENAGE_DRIVER_INVOLVED",           
# "OLDER_DRIVER_INVOLVED",             
# "NIGHT_DARK_CONDITION",              
# "SINGLE_VEHICLE",                    
# "DISTRACTED_DRIVING",                
# "DROWSY_DRIVING",                   
# "ROADWAY_DEPARTURE"
], axis=1)
df = df.dropna()

C:\Users\whyri\AppData\Local\Temp\ipykernel_23908\4024673025.py:2: DtypeWarning: Columns (0,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./Utah_Crash_Data_2020.csv")

In [8]:
df= df[df["CRASH_SEVERITY_ID"] >= 4]
df = df.drop("CRASH_SEVERITY_ID",axis=1)
len(df)

5612

In [9]:
#Takes around 2:30 min to run
df["CRASH_MONTH"] = pd.to_datetime(df["CRASH_DATETIME"]).dt.month
df["CRASH_WEEKDAY"] = pd.to_datetime(df["CRASH_DATETIME"]).dt.day_name()
df["CRASH_HOUR"] = pd.to_datetime(df["CRASH_DATETIME"]).dt.hour

df = df.drop(columns=["CRASH_DATETIME"])
df

,WORK_ZONE_RELATED,PEDESTRIAN_INVOLVED,BICYCLIST_INVOLVED,MOTORCYCLE_INVOLVED,IMPROPER_RESTRAINT,UNRESTRAINED,DUI,INTERSECTION_RELATED,WILD_ANIMAL_RELATED,DOMESTIC_ANIMAL_RELATED,...,TEENAGE_DRIVER_INVOLVED,OLDER_DRIVER_INVOLVED,NIGHT_DARK_CONDITION,SINGLE_VEHICLE,DISTRACTED_DRIVING,DROWSY_DRIVING,ROADWAY_DEPARTURE,CRASH_MONTH,CRASH_WEEKDAY,CRASH_HOUR
7,False,False,False,True,False,False,True,True,False,False,...,False,True,True,False,False,False,False,11,Saturday,19
45,True,True,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,10,Tuesday,0
48,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,9,Tuesday,0
53,False,True,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,12,Saturday,23
78,False,False,False,True,False,False,False,False,False,False,...,False,False,True,False,False,False,False,6,Friday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252453,False,False,False,False,False,False,True,True,False,False,...,False,False,True,False,False,False,False,12,Monday,23
252456,False,False,False,False,True,False,True,False,False,False,...,False,False,True,True,False,False,True,10,Thursday,1
252458,False,False,True,False,False,True,False,True,False,False,...,True,False,False,True,False,False,False,9,Wednesday,20
252469,False,True,False,False,False,False,False,True,False,False,...,False,True,False,True,True,False,False,4,Monday,12
252483,True,True,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,12,Monday,0

In [24]:
# df_agg = df.groupby(['CRASH_MONTH', 'CRASH_WEEKDAY','CRASH_HOUR']).size().reset_index(name="COUNT")
#Although the below columns are numeric, they are categorical because they are a time not a measurement
# df = pd.get_dummies(df, 
# columns=[
#     "CRASH_MONTH",
#     "CRASH_WEEKDAY",
#     "CRASH_HOUR",
#     "WORK_ZONE_RELATED",                 
#     "PEDESTRIAN_INVOLVED",               
#     "BICYCLIST_INVOLVED",                
#     "MOTORCYCLE_INVOLVED",               
#     "IMPROPER_RESTRAINT",                
#     "UNRESTRAINED",                      
#     "DUI",                               
#     "INTERSECTION_RELATED",              
#     "WILD_ANIMAL_RELATED",               
#     "DOMESTIC_ANIMAL_RELATED",           
#     "OVERTURN_ROLLOVER",                 
#     "COMMERCIAL_MOTOR_VEH_INVOLVED",     
#     "TEENAGE_DRIVER_INVOLVED",           
#     "OLDER_DRIVER_INVOLVED",             
#     "NIGHT_DARK_CONDITION",              
#     "SINGLE_VEHICLE",                    
#     "DISTRACTED_DRIVING",                
#     "DROWSY_DRIVING",                   
#     "ROADWAY_DEPARTURE"])
# # df_agg.set_index("COUNT")

df

dfList = []

for col in df:
    if("False" not in col):
        dfList.append((col, sum(df[col]/(5652))))

dfList.sort(key=lambda y: y[1])

for col in dfList:
    print(col)

('DOMESTIC_ANIMAL_RELATED_True', 0.003184713375796177)
('WILD_ANIMAL_RELATED_True', 0.007430997876857752)
('CRASH_HOUR_3', 0.010615711252653922)
('CRASH_HOUR_4', 0.010615711252653922)
('CRASH_HOUR_2', 0.013269639065817395)
('CRASH_HOUR_1', 0.01804670912951167)
('CRASH_HOUR_5', 0.019992922859164902)
('CRASH_HOUR_0', 0.023531493276716234)
('CRASH_HOUR_23', 0.024062278839348934)
('CRASH_HOUR_9', 0.031139419674451597)
('CRASH_HOUR_22', 0.031493276716206726)
('CRASH_HOUR_6', 0.033085633404104794)
('CRASH_HOUR_10', 0.03379334748761505)
('BICYCLIST_INVOLVED_True', 0.03627034677990093)
('CRASH_HOUR_8', 0.039455060155697066)
('WORK_ZONE_RELATED_True', 0.03963198867657463)
('DROWSY_DRIVING_True', 0.03963198867657463)
('CRASH_HOUR_20', 0.04193205944798295)
('CRASH_HOUR_21', 0.04299363057324833)
('CRASH_HOUR_7', 0.04653220099079959)
('CRASH_HOUR_19', 0.05095541401273867)
('CRASH_HOUR_11', 0.052370842179759174)
('CRASH_HOUR_13', 0.056970983722575815)
('CRASH_HOUR_12', 0.05785562632696363)
('CRASH_MONTH_2', 0.05891719745222901)
('IMPROPER_RESTRAINT_True', 0.06192498230714758)
('CRASH_MONTH_3', 0.0640481245576784)
('CRASH_MONTH_1', 0.06440198159943354)
('CRASH_HOUR_18', 0.06705590941259709)
('CRASH_MONTH_12', 0.06900212314225036)
('CRASH_HOUR_14', 0.0693559801840055)
('CRASH_HOUR_15', 0.06988676574663821)
('CRASH_HOUR_16', 0.07183297947629148)
('CRASH_HOUR_17', 0.07607926397735316)
('CRASH_MONTH_4', 0.07696390658174102)
('CRASH_MONTH_11', 0.08421797593772139)
('COMMERCIAL_MOTOR_VEH_INVOLVED_True', 0.08669497523000737)
('CRASH_MONTH_10', 0.08917197452229335)
('DISTRACTED_DRIVING_True', 0.09041047416843634)
('CRASH_MONTH_5', 0.09200283085633447)
('CRASH_MONTH_6', 0.09324133050247746)
('CRASH_MONTH_7', 0.09642604387827372)
('CRASH_MONTH_9', 0.10191082802547839)
('CRASH_MONTH_8', 0.10261854210898867)
('PEDESTRIAN_INVOLVED_True', 0.11111111111111203)
('CRASH_WEEKDAY_Sunday', 0.11978060863411297)
('DUI_True', 0.13128096249115453)
('CRASH_WEEKDAY_Tuesday', 0.13641188959660366)
('CRASH_WEEKDAY_Monday', 0.13800424628450167)
('CRASH_WEEKDAY_Wednesday', 0.13853503184713434)
('UNRESTRAINED_True', 0.139065817409767)
('CRASH_WEEKDAY_Thursday', 0.1447275300778488)
('CRASH_WEEKDAY_Friday', 0.15498938428874706)
('MOTORCYCLE_INVOLVED_True', 0.16029723991507375)
('CRASH_WEEKDAY_Saturday', 0.1604741684359513)
('OLDER_DRIVER_INVOLVED_True', 0.16065109695682886)
('TEENAGE_DRIVER_INVOLVED_True', 0.17038216560509445)
('OVERTURN_ROLLOVER_True', 0.23496107572540245)
('NIGHT_DARK_CONDITION_True', 0.28697806086340977)
('ROADWAY_DEPARTURE_True', 0.3140481245576801)
('INTERSECTION_RELATED_True', 0.3660651096956898)
('SINGLE_VEHICLE_True', 0.46549893842889195)

In [63]:
# Split dataset in features and target variable

y = df_agg["COUNT"] # Label
X = df_agg.drop(columns=["COUNT"]) # Features
X.head()

,CRASH_MONTH_1,CRASH_MONTH_2,CRASH_MONTH_3,CRASH_MONTH_4,CRASH_MONTH_5,CRASH_MONTH_6,CRASH_MONTH_7,CRASH_MONTH_8,CRASH_MONTH_9,CRASH_MONTH_10,...,CRASH_HOUR_14,CRASH_HOUR_15,CRASH_HOUR_16,CRASH_HOUR_17,CRASH_HOUR_18,CRASH_HOUR_19,CRASH_HOUR_20,CRASH_HOUR_21,CRASH_HOUR_22,CRASH_HOUR_23
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [64]:
# Set label and features
y = df_agg["COUNT"] # Label
X = df_agg.drop(columns=["COUNT"]) # Features

# Run the multiple linear regression model
model = sm.OLS(y, X).fit()

# View results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  COUNT   R-squared:                       0.794
Model:                            OLS   Adj. R-squared:                  0.789
Method:                 Least Squares   F-statistic:                     189.7
Date:                Tue, 05 Apr 2022   Prob (F-statistic):               0.00
Time:                        18:59:58   Log-Likelihood:                -10369.
No. Observations:                2016   AIC:                         2.082e+04
Df Residuals:                    1975   BIC:                         2.105e+04
Df Model:                          40
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
CRASH_MONTH_1             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_2             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_3             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_4             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_5             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_6             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_7             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_8             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_9             5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_10            5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_11            5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_MONTH_12            5.78e+12    1.2e+14      0.048      0.961   -2.29e+14    2.41e+14
CRASH_WEEKDAY_Friday    -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_WEEKDAY_Monday    -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_WEEKDAY_Saturday  -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_WEEKDAY_Sunday    -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_WEEKDAY_Thursday  -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_WEEKDAY_Tuesday   -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_WEEKDAY_Wednesday -8.328e+12   1.72e+14     -0.048      0.961   -3.47e+14     3.3e+14
CRASH_HOUR_0             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_1             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_2             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_3             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_4             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_5             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_6             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_7             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_8             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_9             2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_10            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_11            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_12            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_13            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_14            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_15            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_16            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_17            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_18            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_19            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_20            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_21            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_22            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
CRASH_HOUR_23            2.548e+12   5.28e+13      0.048      0.961   -1.01e+14    1.06e+14
==============================================================================
Omnibus:                      127.932   Durbin-Watson:                   0.612
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              322.753
Skew:                           0.358   Prob(JB):                     8.22e-71
Kurtosis:                       4.825   Cond. No.                     2.68e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.53e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [65]:
df_insample = pd.DataFrame({'Actual':df_agg['COUNT'], 
                    'Predicted':model.fittedvalues, 
                    'Residuals (Error)':df_agg['COUNT'] - model.fittedvalues})

df_insample.head(10)

   Actual   Predicted  Residuals (Error)
0      54   86.324219         -32.324219
1      38   64.187500         -26.187500
2      29   58.324219         -29.324219
3      34   54.785156         -20.785156
4      27   57.894531         -30.894531
5      65   79.753906         -14.753906
6     154  120.574219          33.425781
7     252  197.996094          54.003906
8     269  211.812500          57.187500
9     203  166.664062          36.335938

In [67]:
def regression_fit(model, y_actual):

    y_pred = model.fittedvalues

    print(f"R2:\t{round(model.rsquared, 4)}")
    print(f"R2-adj:\t{round(model.rsquared_adj, 4)}")
    print(f"MAE:\t{round(abs(y_pred - y_actual).mean(), 4)}")
    print(f"RMSE:\t{round(((y_pred - y_actual)**2).mean() ** (1/2), 4)}")

regression_fit(model, y)

R2:	0.7935
R2-adj:	0.7893
MAE:	30.9245
RMSE:	41.4398

In [73]:
print("MAX: ", df_agg['COUNT'].max())
print("MIN: ", df_agg['COUNT'].min())
print("MEAN: ", df_agg['COUNT'].mean())
print("MEDIAN: ", df_agg['COUNT'].median())

MAX:  535
MIN:  4
MEAN:  125.24702380952381
MEDIAN:  110.0